version: "3.1"

services:
  bff:
    container_name: bibliyomani-bff
    image: bibliyomani-standalone-bff:20032023
    restart: always
    ports:
      - 8090:8080
    volumes:
      - ./book.sqlite:/book.sqlite
    networks:
      - bibliyomani

  ui:
    container_name: bibliyomani-ui
    image: bibliyomani-ui
    restart: always
    ports:
      - 8091:80
    depends_on:
      - bff
    networks:
      - bibliyomani

networks:
  bibliyomani:
    name: bibliyomani