spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
        show_sql: true
  datasource:
    url: jdbc:sqlite:book.sqlite
    driverClassName: org.sqlite.JDBC
